repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: fix-encoding-pragma
  - id: flake8
  - id: trailing-whitespace

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      args: [--line-length=120, --safe]
      language_version: python3.6